# Generated by Django 4.2.6 on 2024-08-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_serial_number', models.CharField(max_length=20, unique=True)),
                ('truck_model', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('inspection_id', models.AutoField(primary_key=True, serialize=False)),
                ('inspector_name', models.CharField(max_length=255)),
                ('date_time_inspection', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField()),
                ('service_meter_hours', models.DecimalField(decimal_places=4, max_digits=10)),
                ('inspector_signature', models.ImageField(upload_to='signatures/')),
                ('customer_name', models.CharField(max_length=255)),
                ('cat_customer_id', models.CharField(max_length=50, unique=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='backend.truck')),
            ],
        ),
    ]
