# Generated by Django 4.2.6 on 2024-08-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='inspector_name',
        ),
    ]
