# Generated by Django 4.2.6 on 2024-08-10 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_inspector_inspection_inspector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspector',
            options={},
        ),
        migrations.AlterModelManagers(
            name='inspector',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='email',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='password',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='username',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='backend.inspector'),
        ),
    ]
