# Generated by Django 4.2.6 on 2024-08-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_inspector_options_alter_inspector_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='inspector_signature',
        ),
        migrations.AddField(
            model_name='inspection',
            name='details',
            field=models.FileField(default=1, upload_to='inspections/'),
            preserve_default=False,
        ),
    ]
