# Generated by Django 4.2.6 on 2024-08-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_inspection_inspector_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='cat_customer_id',
            field=models.CharField(max_length=50),
        ),
    ]
